#+TITLE:DSC 101 Fall 2021 Syllabus
#+AUTHOR: Marcus Birkenkrahe
#+SUBTITLE: Data Science Methods and Tools
#+options: toc:nil
* General Course Information

  * Meeting Times: Tuesday & Thursday, 13:00-14:15 hrs
  * Meeting place: Derby 209 (CS research lab)
  * Professor: Marcus Birkenkrahe
  * Office: Derby 210
  * Phone: (501) 422-4725
  * Office hours: Mon/Wed/Fri 10:00-10:30 AM; Tue/Thu 4-4:30 PM
  * Text: /The Art of R Programming - A Tour of Statistical Software
    Design/, by Norman Matloff, NoStarch Press (2011).

** Objectives

   Data science is about how to get data to work for us, to give us its
   hidden treasures. Data science has been called "the sexiest job of
   the 21st century". Even if you don't want to become a professional
   data scientist, it’s helpful to master the basic concepts if you
   want to succeed in today's highly data-driven business
   environment. This courses focuses on: data science basics,
   visualization and productivity tools. The course is for everyone who
   is interested in becoming more data literate and growing their skill
   stack. Besides short, synchronous lectures and practice sessions,
   you can learn from weekly quizzes, exercises and a plethora of
   other, custom-built online materials.

** Student Learning Outcomes

   Students who complete DSC101 are able to:

   * Organize data visually in a way that is clear and informative
   * Find and use data sets from the real world
   * Easily and quickly format data into graphs
   * Understand and present statistical information
   * Understand how modern productivity tools can help you
   * Complete an exploratory data analysis project in small steps

** Course requirements

   No prior knowledge required. Both the necessary programming and
   statistical concepts are introduced in the course using examples and
   simple mini-projects. Previous programming experience is useful but
   not mission-critical. Curiosity is essential. You will gain data
   literacy skills by taking this course.

** Grading system

   |-----------+----------------------+--------+--------|
   | When      | Description          | Impact | Graded |
   |-----------+----------------------+--------+--------|
   | Weekly    | DataCamp assignment  |    15% | No     |
   | Weekly    | Weekly tests         |    15% | No     |
   | Last week | Project presentation |    30% | Yes    |
   | TBD       | Final exam           |    40% | Yes    |
   |-----------+----------------------+--------+--------|

*** Grading table

    This table is used to convert completion rates into letter
    grades. For the midterm results, letter grades still carry signs,
    while for the term results, only straight letters are given (by
    rounding up).

    |--------+-----------------+---------------|
    |    *%* | *Midterm Grade* | *Final Grade* |
    |--------+-----------------+---------------|
    | 100-98 | A+              |               |
    |  97-96 | A               | A             |
    |  95-90 | A-              |               |
    |--------+-----------------+---------------|
    |  89-86 | B+              |               |
    |  85-80 | B               | B             |
    |  79-76 | B-              |               |
    |--------+-----------------+---------------|
    |  75-70 | C+              |               |
    |  69-66 | C               | C             |
    |  65-60 | C-              |               |
    |--------+-----------------+---------------|
    |  59-56 | D+              |               |
    |  55-50 | D               | D             |
    |--------+-----------------+---------------|
    |   49-0 | F               | F             |
    |--------+-----------------+---------------|

*** DataCamp assignments (15%)

    Chapters of several DataCamp courses will be assigned to you. To
    complete a chapter takes 20-30 minutes per week. If you complete
    these courses, you get data science certificates that you can add
    to your resume (or to career management portals like LinkedIn -
    see [[https://www.linkedin.com/in/birkenkrahe][my LinkedIn profile]] for an example), or frame and put them on
    your wall. Your DataCamp assignment completion rate will enter the
    final grade cumulatively.

*** Tests (15%)

    There will be 30 short multiple choice tests of 5 questions per
    week. Your grade will be computed from your average completion rate
    over all tests.

*** Project presentation (30%)

    In the last week, you present the results of an agile explorative
    data analysis (EDA) team project. We use the agile Scrum
    methodology throughout the term, which means that you will present
    prototype results during four sprint reviews (about once every four
    weeks), the last of which is the final product or project
    presentation.

    Note that only the final presentation will be graded according to
    the grading table. Detailed grading criteria for the presentation
    will be given in class in the form of a rubric.

*** Exam (40%)

    The final exam will consist of a subset of the weekly test
    questions, possibly with some slight variations to make it more
    interesting. The basic idea is that you can use the tests to
    prepare yourself for the exam. The completion rate of the final
    exam will enter the final grade according to the grading table.

** Grading examples
*** Example - Midterm grade

    At midterms, student X has achieved the following results:

    | *Grade part*         | *Weight* | *Result* |
    |----------------------+----------+----------|
    | Tests                |      15% | 72%      |
    | DataCamp assignment  |      15% | 100%     |

    # Student X's midterm result is computed as follows:
    # #+begin_src R :session :results output
    #   ## midterm weights (only tests and datacamp assignments)
    #   weight_m <- c("tests"=0.5,
    #                 "datacamp"=0.5)
    #   ## results vector
    #   result_m <- c("tests"=72,
    #                 "datacamp"=100)
    #   ## midterm grade
    #   grade_m <-
    # 	weight_m["tests"] * result_m["tests"] +
    # 	weight_m["datacamp"] * result_m["datacamp"]
    #   names(grade_m) <- NULL
    #   grade_m
    # #+end_src

    Student X's midterm result is a "B+" (~86%~).

*** Example - Final grade

    After the finals, student X has achieved the following results:

    | *Grade part*         | *Weight* | *Result* |
    |----------------------+----------+----------|
    | Tests                |      15% |      72% |
    | DataCamp assignment  |      15% |     100% |
    | Project presentation |      30% |      95% |
    | Final exam           |      40% |      90% |

    # Student X's midterm result is computed as follows:
    # #+begin_src R :session :results output
    #   ## full term weight vector according to grading table
    #   weight <- c("exam"= 0.4,
    #               "project"=0.3,
    #               "tests"=0.15,
    #               "datacamp"=0.15)
    #   ## results vector
    #   result <- c("exam"=90,
    #               "project"=95,
    #               "tests"=72,
    #               "datacamp"=100)
    #   ## midterm grade
    #   grade <-
    # 	weight["exam"] * result["exam"] +
    # 	weight["project"] * result["project"] +
    # 	weight["tests"] * result["tests"] +
    # 	weight["datacamp"] * result["datacamp"]
    #   names(grade) <- NULL
    #   grade
    # #+end_src

    Student X's midterm result is an "A" (~90.3%~).

* Standard Policies
** Honor Code

   All graded work in this class is to be pledged in accordance with
   the Lyon College Honor Code. The use of a phone for any reason
   during the course of an exam is considered an honor code
   violation.

** Class Attendance Policy

   Students are expected to attend all class periods for the courses
   in which they are enrolled. They are responsible for conferring
   with individual professors regarding any missed
   assignments. Faculty members are to notify the Registrar when a
   student misses the equivalent of one, two, three, and four weeks
   of class periods in a single course. Under this policy, there is
   no distinction between “excused” and “unexcused” absences, except
   that a student may make up work missed during an excused
   absence. A reminder of the college’s attendance policy will be
   issued to the student at one week, a second reminder at two weeks,
   a warning at three weeks, and notification of administrative
   withdrawal and the assigning of an “F” grade at four
   weeks. Students who are administratively withdrawn from more than
   one course will be placed on probation or suspended.

** Disabilities

   Students seeking reasonable accommodations based on documented
   learning disabilities must contact Danell Hetrick in the Morrow
   Academic Center at (870) 307-7021 or at danell.hetrick@lyon.edu.

** Harassment, Discrimination, and Sexual Misconduct

   Title IX and Lyon’s policy prohibit harassment, discrimination and
   sexual misconduct. Lyon encourages anyone experiencing harassment,
   discrimination or sexual misconduct to talk to Lai-Monte Hunter,
   Title IX Coordinator and Vice-President for Student Life, or
   Sh’Nita Mitchell, Title IX Investigator and Associate Dean for
   Residence Life, about what happened so they can get the support
   they need and Lyon can respond appropriately.  Lyon is legally
   obligated to respond to reports of sexual misconduct, and
   therefore we cannot guarantee the confidentiality of a report,
   unless made to a confidential resource (Chaplain, Counselor, or
   Nurse). As a faculty member, I am required to report possible
   Title IX violations and must provide our Title IX coordinator with
   all relevant details.  I cannot, therefore, guarantee
   confidentiality.

** College-Wide COVID-19 Policies for Fall, 2021

   Masks are mandated for all students in classrooms, laboratories and studios.  They remain optional for all persons on the Lyon campus in all other locations and outside.
   Participation in community surveillance testing in mandatory.
   Vaccines are STRONGLY encouraged for all faculty, staff, and students. Vaccines are NOT MANDATED for Lyon College community members.

   Details specific to this course may be found in the subsequent pages of this syllabus. Those details will include at least the following:
   A description of the course consistent with the Lyon College catalog.
   A list of student learning outcomes for the course.
   A summary of all course requirements.
   An explanation of the grading system to be used in the course.
   Any course-specific attendance policies that go beyond the College policy.
   Details about what constitutes acceptable and unacceptable student collaboration on graded work.

* Course specific information
** Assignments and Honor Code

   There will be numerous assignments during the semester -
   programming, lessons, tests, and sprint reviews. They are due at
   the beginning of the class period on the due date. Once class
   begins, the assigment will be considered one day late if it has not
   been turned in.  Late programs will not be accepted without an
   extension.  Extensions will *not* be granted for reasons such as:

   * You could not get to a computer
   * You could not get a computer to do what you wanted it to do
   * The network was down
   * The printer was out of paper or toner
   * You erased your files, lost your homework, or misplaced your
     flash drive
   * You had other coursework or family commitments that interfered
     with your work in this course

   Put “Pledged” and a note of any collaboration in the comments of
   any program you turn in. Programming assignments are individual
   efforts, but you may seek assistance from another student or the
   course instructor.  You may not copy someone else’s solution. If
   you are having trouble finishing an assignment, it is far better to
   do your own work and receive a low score than to go through an
   honor trial and suffer the penalties that may be involved.

   What is cheating on an assignment? Here are a few examples:

   * Having someone else write your assignment, in whole or in part
   * Copying an assignment someone else wrote, in whole or in part
   * Collaborating with someone else to the extent that your
     submissions are identifiably very similar, in whole or in part
   * Turning in a submission with the wrong name on it

   What is not cheating?  Here are some examples:

   * Talking to someone in general terms about concepts involved in
     an assignment
   * Asking someone for help with a specific error message or bug in
     your program
   * Getting help with the specifics of language syntax or citation
     style
   * Utilizing information given to you by the instructor

   Any assistance must be clearly explained in the comments at the
   beginning of your submission.  If you have any questions about
   this, please ask or review the policies relating to the Honor Code.

   Absences on Days of Exams:

   Test “make-ups” will only be allowed if arrangements have been
   made prior to the scheduled time.  If you are sick the day of the
   test, please e-mail me or leave a message on my phone before the
   scheduled time, and we can make arrangements when you return.

** Important Dates:

   | *Date*         | *Description*                              |
   |----------------+--------------------------------------------|
   | August 30      | Last day to drop w/o record of a course    |
   | September 6    | Labor day (no classes)                     |
   | October 2-5    | Fall break (no classes)                    |
   | October 6      | Mid-semester grade reports due             |
   | October 13     | Last day to drop a course with a "W" grade |
   | October 20     | Service day on campus (no classes)         |
   | Nobember 24-28 | Thanksgiving Break (no classes)            |
   | December 3     | Last day of class                          |
   | December 6-10  | Final exams                                |
   | December 15    | Final grades due                           |

** Schedule and session content

   | Date   | Lectures                | Assignments             |
   |--------+-------------------------+-------------------------|
   | 17-Aug | *Course overview*       |                         |
   | 19-Aug | *Data science overview* | Intro to Basics         |
   | 24-Aug | *The R shell*           |                         |
   | 26-Aug | *The R environment*     | Vectors                 |
   | 31-Aug | *Vectors*               |                         |
   | 2-Sep  | *Data frames*           | Matrices                |
   | 7-Sep  | *Factor vectors*        |                         |
   | 9-Sep  | *Lists in R*            | Factors                 |
   | 14-Sep | *~Nile~ exploration*    |                         |
   | 16-Sep | *Visualization*         | Data frames             |
   | 21-Sep | *Base R graphics*       |                         |
   | 23-Sep | *Literate Programming*  | Lists                   |
   | 28-Sep | Iteration I             |                         |
   | 30-Sep | Fibonacci series        | Conditionals            |
   | 7-Oct  | Conditions              | Loops                   |
   | 12-Oct | EDA example I           |                         |
   | 14-Oct | Linear regression I     | Functions               |
   | 19-Oct | Object-orientation      |                         |
   | 21-Oct | EDA example II          | The apply family        |
   | 26-Oct | Packages                |                         |
   | 28-Oct | Grammar of Graphics     | Base R graphics         |
   | 2-Nov  | Functional Programming  |                         |
   | 4-Nov  | Text mining I           | Different plot types    |
   | 9-Nov  | Text mining II          |                         |
   | 11-Nov | Linear regression II    | Adding details to plots |
   | 16-Nov | Dates and times         |                         |
   | 18-Nov | Coding style            | How much is too much    |
   | 23-Nov | Logistic regression     |                         |
   | 30-Nov | Team presentations      | Plot customization      |
   | 2-Dec  | Team presentations      |                         |
