#+OPTIONS: toc:nil
* Base R Plotting

  This repo contains problem and solution notebooks for plotting with
  base R functions. 

  | FILE ~.ipynb~     | DESCRIPTION                              |
  |-------------------+------------------------------------------|
  | ~plotting~        | Base R plotting with ~plot()~            |
  | ~adding_details~  | Adding details to an existing plot[fn:2] |
  | ~different_plots~ | Different base R plot types[fn:1]        |

  You find a summary of functions with examples in the file
  ~cheatsheet.pdf~ (Gerard, 2017). Paradoxically, the author
  reproduced ~ggplot2~ plots using base R, which is the wrong way
  around, because ~ggplot2~ is a fairly recent addition to R
  (ca. 2016). But it is superbly successful for pretty plotting.

  In my view, solid knowledge of base R methods beats broad knowledge
  of arcane packages especially for interactive, exploratory EDA. When
  you're presenting, many other options exist - but exploration is key
  because it's content, not form.

* References

  Gerard, D (August 8, 2017). Base R Graphics Cheat Sheet [repo]. [[https://dcgerard.github.io/stat234/base_r_cheatsheet.html][URL:
  dcgerard.github.io]].

* Footnotes

[fn:2]Based on Davies' treatment in Book of R (2016).

[fn:1]Compare with the DataCamp course "Data Visualization with R" by
Ron Pearson (2017) for some details.
